#!/bin/bash
# Comprehensive Backtest Validation Script for DidiBot Stop Loss System
# This script provides guidance for validating the stop loss implementation

echo "=================================="
echo "DidiBot Stop Loss Backtest Guide"
echo "=================================="
echo ""

echo "PHASE 1: PREPARATION"
echo "===================="
echo "1. Compile DidiBot.mq5 in MetaEditor (F7)"
echo "2. Ensure historical data is available for test symbols"
echo "3. Configure Strategy Tester settings in MT5"
echo ""

echo "PHASE 2: TEST CONFIGURATIONS"
echo "============================"
echo ""

echo "TEST 1: ATR-Based Conservative"
echo "------------------------------"
echo "Parameters:"
echo "  InpStopType = ATR_BASED"
echo "  InpATRMultiplier = 1.0"
echo "  InpTrailingEnabled = true"
echo "  InpMaxStopPips = 50"
echo "  Period: 2023.01.01 - 2023.12.31"
echo "  Symbols: EURUSD, GBPUSD"
echo "  Timeframes: M15, H1"
echo "  Expected: Lower drawdown, moderate returns"
echo ""

echo "TEST 2: ATR-Based Balanced"
echo "-------------------------"
echo "Parameters:"
echo "  InpStopType = ATR_BASED"
echo "  InpATRMultiplier = 1.5"
echo "  InpTrailingEnabled = true"
echo "  InpMaxStopPips = 100"
echo "  Period: 2023.01.01 - 2023.12.31"
echo "  Symbols: EURUSD, GBPUSD, USDJPY"
echo "  Timeframes: M15, H1, H4"
echo "  Expected: Balanced risk/reward"
echo ""

echo "TEST 3: ATR-Based Aggressive"
echo "----------------------------"
echo "Parameters:"
echo "  InpStopType = ATR_BASED"
echo "  InpATRMultiplier = 2.5"
echo "  InpTrailingEnabled = false"
echo "  InpMaxStopPips = 200"
echo "  Period: 2023.01.01 - 2023.12.31"
echo "  Symbols: GBPJPY, EURGBP"
echo "  Timeframes: H1, H4"
echo "  Expected: Higher returns, higher risk"
echo ""

echo "TEST 4: Fixed Pip Comparison"
echo "---------------------------"
echo "Parameters:"
echo "  InpStopType = FIXED_PIPS"
echo "  InpFixedPips = 30, 50, 80"
echo "  InpTrailingEnabled = true"
echo "  Period: 2023.01.01 - 2023.12.31"
echo "  Symbols: EURUSD"
echo "  Timeframes: M15, H1"
echo "  Expected: Consistent stop distances"
echo ""

echo "TEST 5: Volatile Market Conditions"
echo "---------------------------------"
echo "Parameters:"
echo "  InpStopType = ATR_BASED"
echo "  InpATRMultiplier = 2.0"
echo "  InpTrailingEnabled = true"
echo "  Period: March 2020 (COVID volatility)"
echo "  Symbols: EURUSD, GBPUSD, USDJPY"
echo "  Timeframes: M15, H1"
echo "  Expected: ATR adaptation to volatility"
echo ""

echo "PHASE 3: VALIDATION CHECKLIST"
echo "=============================="
echo ""

echo "Performance Metrics to Monitor:"
echo "✓ Total Return (%)"
echo "✓ Maximum Drawdown (%)"
echo "✓ Profit Factor"
echo "✓ Win Rate (%)"
echo "✓ Average Win vs Average Loss"
echo "✓ Number of trades"
echo "✓ Recovery Factor (Profit/Max Drawdown)"
echo ""

echo "Stop Loss Specific Metrics:"
echo "✓ Stop loss hit rate (%)"
echo "✓ Average stop distance (pips)"
echo "✓ Trailing stop adjustments count"
echo "✓ Error recovery success rate"
echo "✓ ATR calculation timing (ms)"
echo ""

echo "Error Handling Validation:"
echo "✓ No missing stop losses"
echo "✓ No invalid stop distances"
echo "✓ Proper error logging"
echo "✓ Network error recovery"
echo "✓ Broker rejection handling"
echo ""

echo "PHASE 4: EXECUTION STEPS"
echo "========================"
echo ""

echo "1. MetaTrader 5 Strategy Tester Setup:"
echo "   - Open MetaTrader 5"
echo "   - Go to View > Strategy Tester"
echo "   - Select DidiBot from Expert Advisor list"
echo "   - Configure symbol and timeframe"
echo "   - Set date range and modeling quality"
echo ""

echo "2. Parameter Configuration:"
echo "   - Click 'Expert Properties' in Strategy Tester"
echo "   - Go to 'Inputs' tab"
echo "   - Configure stop loss parameters as per test scenarios"
echo "   - Enable 'Visual mode' for detailed observation"
echo ""

echo "3. Log Analysis:"
echo "   - Monitor 'Journal' tab for error messages"
echo "   - Check 'Experts' tab for trade execution logs"
echo "   - Verify stop loss placement and adjustments"
echo "   - Confirm error recovery mechanisms"
echo ""

echo "4. Results Documentation:"
echo "   - Save test reports for each configuration"
echo "   - Compare performance across different settings"
echo "   - Analyze stop loss effectiveness"
echo "   - Document any issues or improvements needed"
echo ""

echo "PHASE 5: SUCCESS CRITERIA"
echo "=========================="
echo ""

echo "Stop Loss System is considered VALIDATED if:"
echo ""

echo "Functional Requirements:"
echo "✓ ATR-based stops calculate correctly"
echo "✓ Fixed pip stops place at exact distances"
echo "✓ Trailing stops adjust in favorable direction only"
echo "✓ Maximum stop distance limits are respected"
echo "✓ Stop losses visualize correctly on charts"
echo ""

echo "Performance Requirements:"
echo "✓ ATR calculations complete in <10ms"
echo "✓ Trailing stop checks complete in <50ms"
echo "✓ Cache hit rate >70% for ATR values"
echo "✓ Error recovery success rate >90%"
echo "✓ No memory leaks during extended testing"
echo ""

echo "Integration Requirements:"
echo "✓ Compatible with existing Didi signals"
echo "✓ Position sizing works with stop distances"
echo "✓ Chart visualization functions properly"
echo "✓ Information panel updates correctly"
echo "✓ No interference with other EA functions"
echo ""

echo "Risk Management Requirements:"
echo "✓ No trades without stop losses"
echo "✓ Stop distances respect broker minimums"
echo "✓ Risk per trade remains within limits"
echo "✓ Trailing stops protect profits effectively"
echo "✓ Error conditions don't create excessive risk"
echo ""

echo "PHASE 6: REPORTING TEMPLATE"
echo "============================"
echo ""

echo "Test Report Format:"
echo "==================="
echo ""
echo "Test Name: [Configuration Description]"
echo "Date Range: [Start Date] to [End Date]"
echo "Symbol: [Trading Symbol]"
echo "Timeframe: [Chart Timeframe]"
echo ""
echo "Parameters:"
echo "- Stop Type: [ATR_BASED/FIXED_PIPS]"
echo "- ATR Multiplier: [Value]"
echo "- Fixed Pips: [Value]"
echo "- Trailing Enabled: [true/false]"
echo "- Max Stop Pips: [Value]"
echo ""
echo "Results:"
echo "- Total Return: [%]"
echo "- Max Drawdown: [%]"
echo "- Profit Factor: [Value]"
echo "- Win Rate: [%]"
echo "- Total Trades: [Count]"
echo "- Stop Hit Rate: [%]"
echo "- Avg Stop Distance: [Pips]"
echo "- Trailing Adjustments: [Count]"
echo ""
echo "Issues Found:"
echo "- [List any errors or problems]"
echo ""
echo "Recommendations:"
echo "- [Suggested improvements]"
echo ""

echo "EXECUTION COMPLETE"
echo "=================="
echo "Follow this guide to comprehensively validate the DidiBot stop loss system."
echo "Ensure all test scenarios pass before deploying to live trading."
echo ""
echo "For technical support, review the logs in:"
echo "- MT5 Strategy Tester Journal"
echo "- MT5 Experts tab"
echo "- DidiBot console output"
echo ""
echo "Good luck with your backtesting!"
